### ISSUE TITLE
feature request: add support for PEP 735 `[dependency-groups]`

### ISSUE THREAD

**Issue by radusuciu** [zehengl/pip-check-updates#184]
I recently started using these in `uv` which implements [PEP 735](https://peps.python.org/pep-0735/). This is probably a pretty complex feature. Here is an example from the PEP:

```toml
[dependency-groups]
group-a = ["foo"]
group-b = ["foo>1.0"]
group-c = ["foo<1.0"]
all = ["foo", {include-group = "group-a"}, {include-group = "group-b"}, {include-group = "group-c"}]
```
